<<<<<<< HEAD
# Generated by Django 4.1.3 on 2022-11-02 10:42
=======
# Generated by Django 4.1.3 on 2022-11-18 18:32
>>>>>>> d169fc24b86a22d81980091a83440a448135d396

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Flashcards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
<<<<<<< HEAD
                ('correct_answer', models.CharField(max_length=255)),
                ('wrong_answer1', models.CharField(blank=True, max_length=255, null=True)),
                ('wrong_answer2', models.CharField(blank=True, max_length=255, null=True)),
                ('wrong_answer3', models.CharField(blank=True, max_length=255, null=True)),
=======
>>>>>>> d169fc24b86a22d81980091a83440a448135d396
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
<<<<<<< HEAD
=======
            options={
                'verbose_name_plural': 'Flashcards',
            },
>>>>>>> d169fc24b86a22d81980091a83440a448135d396
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('answer', models.CharField(max_length=255)),
=======
                ('content', models.CharField(max_length=255)),
>>>>>>> d169fc24b86a22d81980091a83440a448135d396
                ('correct', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flashcards.flashcards')),
<<<<<<< HEAD
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
=======
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
>>>>>>> d169fc24b86a22d81980091a83440a448135d396
        ),
    ]
