# Generated by Django 4.1.3 on 2022-11-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='Flashcards.flashcards'),
        ),
    ]
