# Generated by Django 4.1.3 on 2022-11-21 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topics',
            name='name',
            field=models.CharField(db_collation='und-x-icu', max_length=255),
        ),
    ]
