# Generated by Django 4.1.3 on 2022-11-19 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0003_flashcards_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flashcards.categories'),
        ),
    ]
