# Generated by Django 4.1.3 on 2022-11-20 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0004_alter_flashcards_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='type',
            field=models.CharField(blank=True, choices=[('input', 'input'), ('radio', 'radion')], max_length=255, null=True),
        ),
    ]
