# Generated by Django 4.1.3 on 2022-11-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0005_flashcards_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcards',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flashcards',
            name='type',
            field=models.CharField(blank=True, choices=[('input', 'input'), ('radio', 'radio')], max_length=255, null=True),
        ),
    ]
