# Generated by Django 4.1.3 on 2022-11-21 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0006_flashcards_is_verified_alter_flashcards_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcards',
            name='type',
            field=models.CharField(choices=[('input', 'input'), ('radio', 'radio')], max_length=255),
        ),
    ]
