# Generated by Django 4.1.3 on 2022-11-30 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0002_topics_category'),
        ('Flashlists', '0003_alter_flashlists_flashcards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashlists',
            name='flashcards',
            field=models.ManyToManyField(blank=True, to='Flashcards.flashcards'),
        ),
    ]
