# Generated by Django 4.1.3 on 2022-11-30 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0002_topics_category'),
        ('Flashlists', '0004_alter_flashlists_flashcards'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashlists',
            name='flashcards',
        ),
        migrations.CreateModel(
            name='FlashlistsElements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('flashcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flashcards.flashcards')),
                ('flashlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flashlists.flashlists')),
            ],
            options={
                'verbose_name_plural': 'Elements',
            },
        ),
    ]
