# Generated by Django 4.1.3 on 2022-11-30 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashlists', '0005_remove_flashlists_flashcards_flashlistselements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashlistselements',
            name='flashlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashlist', to='Flashlists.flashlists'),
        ),
    ]
