# Generated by Django 4.1.3 on 2022-11-30 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashlists', '0006_alter_flashlistselements_flashlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashlistselements',
            name='flashlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elements', to='Flashlists.flashlists'),
        ),
    ]
