# Generated by Django 4.1.3 on 2022-11-30 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0002_topics_category'),
        ('Flashlists', '0008_alter_flashlistselements_flashlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashlistselements',
            name='flashcard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashlists', to='Flashcards.flashcards'),
        ),
        migrations.AlterUniqueTogether(
            name='flashlistselements',
            unique_together={('flashlist', 'flashcard')},
        ),
    ]
