# Generated by Django 4.1.3 on 2022-11-03 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0003_alter_notes_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='category',
            field=models.CharField(choices=[('Matematyka', 'Matematyka'), ('Biologia', 'Biologia'), ('Chemia', 'Chemia'), ('Fizyka', 'Fizyka'), ('Historia', 'Historia'), ('Geografia', 'Geografia'), ('Informatyka', 'Informatyka'), ('Język Polski', 'Język Polski'), ('Język Angielski', 'Język Angielski')], default='Chemia', max_length=255),
            preserve_default=False,
        ),
    ]
