# Generated by Django 4.1.3 on 2022-11-30 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0004_alter_noteslikes_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
