# Generated by Django 4.1.3 on 2022-11-19 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcards', '0004_alter_flashcards_category'),
        ('Notes', '0004_notes_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Flashcards.categories'),
        ),
    ]
